from classesH import *

animal1 = Cachorro('Koda','brancodido')
animal1.comer()
animal1.latir()
print()
animal2 = Gato('Rocky', 'tricolor')
animal2.comer()
animal2.miar()
print()
animal3 = Coelho('Perna Longa', 'cinza')
animal3.grunhir()
print()
animal4 = Vaca('mimosa', 'malhada')
animal4.mugir()